### ISSUE TITLE
Build-time importing

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-import#1]
As a next step importing can also be implemented at build time using Babel or Webpack.

**Comment by zephraph** [comment]
Is the intent to extend a currently existing graphql loader, setup a loader that only does this transform, or create an entirely new loader that also has this functionality?

**Comment by kbrandwijk** [comment]
Also see https://github.com/graphql-cli/graphql-cli/issues/68

**Comment by giautm** [comment]
Hi, I copied from babel-plugin-inline-import plugin to create a new one: [`babel-plugin-graphql-import`](https://github.com/giautm/babel-plugin-graphql-import)

**Comment by kbrandwijk** [comment]
This has also been implemented by `graphql prepare`.

**Comment by giautm** [comment]
@kbrandwijk : where i can found document or pr related to that command line?
