### ISSUE TITLE
Bug with filtering types when using '*'

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-import#10]
Given the following schemas:
```graphql
# schemaC
    type C1 {
      id: ID!
    }

    type C2 {
      id: ID!
    }

    type C3 {
      id: ID!
    }

# schemaB
    # import * from 'schemaC.graphql'

    type B {
      hello: String!
      c1: C1
      c2: C2
    }`

#schemaA
    # import * from "schemaB.graphql"

    type A {
      # test 1
      first: String @first
      second: Float
      b: B
    }
```
The resulting schema contains all types from all schemas, even though C3 is not used.
Now changing the import in schema A to:
```graphql
#schemaA
    # import B from "schemaB"

    type A {
      # test 1
      first: String @first
      second: Float
      b: B
    }
```
Suddenly, C3 is correctly filtered out.

**Comment by schickling** [comment]
Thanks for reporting this. @kbrandwijk would you (or someone else) mind creating a PR with a new test case for this including a fix?

**Comment by kbrandwijk** [comment]
I will take this into account with the rework discussed in the other issues regarding default/configurable behavior.

**Comment by kbrandwijk** [comment]
This is already fixed in the latest release.
