### ISSUE TITLE
Fix comment in generated schema

### ISSUE THREAD

**Issue by johannpinson** [graphcool/graphql-import#100]
I have a little bug about the syntax in Visual Studio Code, because one comment isn't generated to the new line:

https://github.com/graphcool/graphql-import/blob/4458d2955d9319ca2527b1a770438104a5f3c092/fixtures/complex/b.graphql#L9152-L9156

This is the actual render in VSC:
![capture d ecran 2018-03-08 a 17 29 40](https://user-images.githubusercontent.com/2202989/37162735-53c34f96-22f6-11e8-9f7d-1075c2230385.png)

It seems that the `"""` comment tag must start in a new line to avoid the IDE to misunderstand the color syntax (see the minimap on the right)

It must be like this:
![capture d ecran 2018-03-08 a 17 29 34](https://user-images.githubusercontent.com/2202989/37162842-95327574-22f6-11e8-85bc-11c9aae3301c.png)

Thanks 😀

(PS: maybe also about the VSC plugin to graphQL syntax because I don't have it for Atom)

**Comment by marktani** [comment]
Issue moved to [graphcool/prisma #2047](https://github.com/graphcool/prisma/issues/2047) via [**ZenHub**](https://www.zenhub.com/)
