### ISSUE TITLE
Cannot use object import when providing filepath for `schema`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [graphcool/graphql-import#104]
The title's confusing, so I'll just give an example.
```
# sample.graphql
# import Foo from 'foo'

type Query {
  foo: Foo
}
```
```
// index.js
const {readFileSync} = require('fs');
const {importSchema} = require('graphql-import');

const fooSchema = `
  type Foo {
    id: ID!
  }
`

// This works.
importSchema(readFileSync('./sample.graphql', 'utf8'), {foo: fooSchema});
// This throws.
importSchema('./sample.graphql', {foo: fooSchema});
```
The issue is that it tries to pull `dirname/foo` from `schemas`.

**Comment by SpaceK33z** [comment]
I've tried to reproduce this issue by writing a test, but I can't get it to fail (see [source code](https://github.com/SpaceK33z/graphql-import/commit/d88b772b2bacf4e42c07485f512f0c31bd4ee58b)). Could you confirm this works now?

**Comment by wtgtybhertgeghgtwtg** [comment]
It seems to work now.  Thank you.
