### ISSUE TITLE
Duplicate imports from the same imported file do not work

### ISSUE THREAD

**Issue by SpaceK33z** [graphcool/graphql-import#115]
Given these GraphQL files:

**all.graphql**

```graphql
# import Query.first, Query.second from "a.graphql"
# import Query.third from "a.graphql"
```

**a.graphql**

```graphql
type Query {
  first: String
  second: Float
  third: String
  unused: String
}
```

The actual output is:

```graphql
type Query {
  first: String
  second: Float
}
```

But the expected output is:

```graphql
type Query {
  first: String
  second: Float
  third: String
}
```

In this simple scenario you'd perhaps say: just merge those two imports together. However, this is of course a reduced test case. I want to make a separate file per entity (e.g. user, restaurant) and per file, import the generated Prisma file `# import Query.user from "generated/prisma.graphql"`.

I have also written **[a failing test](https://github.com/SpaceK33z/graphql-import/commit/bd4044291423b945dd0d380d8afa6c93f69d5c8c)**. If you'd like I can make a PR with the failing test. I don't know enough about this package to fix it myself though.

**Comment by schickling** [comment]
Thanks a lot for bringing this up @SpaceK33z. Yeah a PR with a failing test would be a good first step, maybe someone else can pick it up and provide a full fix then?

**Comment by SpaceK33z** [comment]
@schickling thanks, I have since made a PR with the full fix :), see https://github.com/graphcool/graphql-import/pull/140
