### ISSUE TITLE
Unexpected behavior importing

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-import#13]
1. Interface implementations:
I don't understand the intended behavior of the `interface-implements` fixture. Why is it expected that when importing an interface, `graphql-import` does also import all implementations of that interface?

2. Missing types
If you import a Type, that has fields of a Type that is not imported, that Type gets imported automatically. I think this kind of implicit behavior should not happen.

3. 'Tree shaking'
It seems `graphql-import` does some tree shaking, if you do `import *` but one of the types from the imported file is not used. Again, I think this kind of implicit behavior should not happen.

**Comment by schickling** [comment]
Thanks for bringing this up @kbrandwijk. The importing behaviour so far is implemented in a very "broad" way as you mentioned in (1) and (2). This behaviour is expected for a lot of tools such as import types for the sake of selective schema stitching/delegation.

I'd be very interested about the use cases that require a different setting. I suggest to add some kind of configuration functionality to configure the importing strategy.

(3) should probably also be a strategy setting.

**Comment by kbrandwijk** [comment]
Let's compare it to the closest thing: JS/TS imports. If you import a function that uses another function from that same file, you don't have to import that explicitly, so regarding 2, I have changed my mind.

Regarding 1, I see no benefit in importing other implementations of an interface, if I'm not using them in my final schema. 

Regarding 3, yes that would need to be a setting. I want to disable it by default, to discourage (again like JS/TS), to just do `import *` all the time. I think explicit imports make it more clear what you are doing.

**Comment by schickling** [comment]
> Let's compare it to the closest thing: JS/TS imports. If you import a function that uses another function from that same file, you don't have to import that explicitly, so regarding 2, I have changed my mind.

I think you rather have to think in terms of bundling than in terms of importing, since JS/TS still has import functionality at runtime.

**Comment by kbrandwijk** [comment]
Waiting for approval of #16.

**Comment by kbrandwijk** [comment]
Covered by #16
