### ISSUE TITLE
Import should also perform schema validation

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-import#14]
Either directly, or using a separate method. I think it's very helpful to perform standard schema validation. If you agree, I have some WIP on the matter using the standard graphjs/validate method with some custom rules.

**Comment by schickling** [comment]
Yes, sounds great! Would be good to come up with some configuration API (as mentioned in #13) for these kind of settings.

**Comment by kbrandwijk** [comment]
Waiting for approval of #16.

**Comment by kbrandwijk** [comment]
Covered by #16
