### ISSUE TITLE
Node module resolution

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-import#4]
Allow the following:

```graphql
# import Repository from "github-graphql-binding"

type Query {
  repo: Repository
}
```

This could potentially break the existing API by enforcing `./` for local imports.

Would be great to hear more thoughts on this feature proposal!

**Comment by kbrandwijk** [comment]
Also see #11. Moving `import mySchema from 'github-graphql-binding'` into the code file, and leaving `# import Repository from 'mySchema'` in the actual schema.
