### ISSUE TITLE
Import from HTTP endpoints

### ISSUE THREAD

**Issue by schickling** [graphcool/graphql-import#5]
I've heard people asking about the option to import from HTTP endpoints. While this is convenient in simple scenarios, most real-world applications require you to have your schema available locally avoiding the heavy network overhead to download the schema definition from a remote server.

I leave it up for discussion whether this should be implemented or not.

**Comment by kbrandwijk** [comment]
I think #11 is a good compromise. If people insist on having a use case where they don't have the schemas as local files, it will at least leave the burden of supporting every possible scenario for actually going from `import something from 'url'` to actually downloading (proxy, authentication, etc. etc.) out of `graphql-import`.

**Comment by kbrandwijk** [comment]
Closing this as something that will not be part of the core graphql-import.
