### ISSUE TITLE
Support nested imports

### ISSUE THREAD

**Issue by gaurav107** [graphcool/graphql-import#8]
For the following schema in `a.graphql`
```
type Query {
feed: [Post!]!
me: User
}
```
I'd like to be able to do something like this:
In `b.graphql`
```
# import Query.feed from "a.graphql"
```
and that query automatically gets appended to my other queries in b.graphql

**Comment by kbrandwijk** [comment]
@schickling I think this would be a very valuable addition, also based on recent questions on Apollo Slack by others regarding stitching schemas and needing root query/mutation/subscription fields. Are you okay to move ahead with this?

**Comment by schickling** [comment]
I'd love to see some more examples for this and explore other syntax options.

@stubailo @freiksenet do you have an opinion about this?

**Comment by kbrandwijk** [comment]
Apart from `# import Query.feed from 'a.graphql'` (graphql path style) and `# import feed from 'a.graphql/Query'` (js/ts style) I don't see many other options to define this type of import. Also looking forward at getting more input.

**Comment by schickling** [comment]
After thinking a bit about this and seeing more use cases, I like the initially proposed syntax:

```
# import Query.feed from "a.graphql"
```

There are two ways this can be implemented:

1. Using `extend type`

```
extend type Query {
  feed: ...
}

2. Merging all types

Since there isn't final consensus yet around the `extend` syntax, I suggest to go for (2).

**Comment by kbrandwijk** [comment]
Another edge case:
- [ ] Root Type doesn't exist yet

Question:
When you import a type that already exists, what happens now?

**Comment by schickling** [comment]
> When you import a type that already exists, what happens now?
I suggest, it should throw an error.

**Comment by jlengstorf** [comment]
Is this limited to certain types? I can see this getting out of hand if something like this is allowed:

```graphql
# import Store.products

type Store {
  hours
}
```

**Comment by kbrandwijk** [comment]
@jlengstorf It's limited to root types (Query, Mutation, Subscription).

**Comment by marktani** [comment]
What's the final syntax chosen here? I wasn't able to find an example in `README.md`

My use case is that I want to define queries and mutations in separate `queries.graphql` and `mutations.graphql` files. I want to tie them together in a final `schema.graphql` file.

**Comment by marktani** [comment]
Found it in the fixtures:

```
# import Query.* from 'b.graphql'
```

**Comment by ryankauk** [comment]
@marktani Did you get the nesting to work? Was the nested using the prisma.graphql that was generated or only custom? I'm trying to split them apart like you did.
