### ISSUE TITLE
Does this library provide support for custom scalar's?

### ISSUE THREAD

**Issue by gavinwilliams** [graphcool/graphql-import#84]
I would expect to load these through my application rather than import schema's in my graphql files.

Instead I get:

```
Error: Field event: Couldn't find type GraphQLUUID in any of the schemas.
    at collectNode (/Users/XXX/XXX/XXX/XXX/XXX/XXX/node_modules/graphql-import/src/definition.ts:154:15)
    at /Users/XXX/XXX/XXX/XXX/XXX/XXX/node_modules/graphql-import/src/definition.ts:135:7
    at Array.forEach (<anonymous>)
    at collectNewTypeDefinitions (/Users/XXX/XXX/XXX/XXX/XXX/XXX/node_modules/graphql-import/src/definition.ts:134:26)
    at Object.completeDefinitionPool (/Users/XXX/XXX/XXX/XXX/XXX/XXX/node_modules/graphql-import/src/definition.ts:49:39)
    at importSchema (/Users/XXX/XXX/XXX/XXX/XXX/XXX/node_modules/graphql-import/src/index.ts:106:26)
```

**Comment by schickling** [comment]
Hmm great point! I think right now custom scalars are not yet supported but would be great if you could create a PR for that. 🙏

**Comment by gavinwilliams** [comment]
@schickling how would you recommend implementing this? I'm thinking of just adding an additional param with an array of custom scalar types. It doesn't look like we need to do anything with the scalar's other than to check to see if they exist.

**Comment by schickling** [comment]
Just to clarify, the result of importing scalar types is that they are part of the imported SDL string. So there won't be any additional parameter necessary, it's just missing functionality right now.

**Comment by gavinwilliams** [comment]
@schickling it's ok, I managed to fix this by just creating scalar .graphql files.

**Comment by ahmadsn26** [comment]
Hi gavin could you please share a bit of details on how to get this done ... i am also facing the same thing and it would be of great help if i can add a custom scalar type in my case its a json type

**Comment by amitava82** [comment]
> @schickling it's ok, I managed to fix this by just creating scalar .graphql files.

How did you do it?
