### ISSUE TITLE
parseSDL startsWith import

### ISSUE THREAD

**Issue by djeeg** [graphcool/graphql-import#94]
Hi, thanks for the library! starting to use it to break apart my schema file, looks very promising

Small question, would you be open to changing this line?

https://github.com/graphcool/graphql-import/blob/master/src/index.ts#L63

`.filter(l => l.startsWith('# import') || l.startsWith('#import'))`

to (ie spaces after import)

`.filter(l => l.startsWith('# import ') || l.startsWith('#import '))`

Our team have a tendancy to add comments lines like this:

> #importent: DONT add types that will causes import cycles

And those lines get rejected by here:
https://github.com/graphcool/graphql-import/blob/master/src/index.ts#L39

**Comment by schickling** [comment]
Absolutely, great point! Please create a PR! :)
